// SPDX-FileCopyrightText: 2024 Softbear, Inc.
// SPDX-License-Identifier: AGPL-3.0-or-later

const BOT_NAMES: [&str; 70] = [
    "admedia bot",
    "adsbot-google",
    "ahrefsbot",
    "alkalinebot",
    "araybot",
    "archive.org_bot",
    "bbot",
    "bingbot",
    "bitlybot",
    "blekkobot",
    "borg-bot",
    "bot",
    "botlink",
    "boxseabot",
    "careerbot",
    "compspybot",
    "confuzzledbot",
    "contextad bot",
    "coolbot",
    "crystalsemanticsbot",
    "diffbot",
    "diibot",
    "dragonbot",
    "elfinbot",
    "exabot",
    "ezooms.bot",
    "friendfeedbot",
    "gigabot",
    "googlebot",
    "hambot",
    "iajabot",
    "internet cruiser robot",
    "irobot",
    "jbot",
    "ko_yappo_robot",
    "linkedinbot",
    "mail.ru_bot",
    "mj12bot",
    "msnbot",
    "musobot",
    "news bot",
    "paperlibot",
    "psbot",
    "psbot",
    "rixbot",
    "robot",
    "semrushbot",
    "seznambot",
    "simbot",
    "skimbot",
    "socialradarbot",
    "solbot",
    "spbot",
    "spiderbot",
    "techbot",
    "tweetedtimes bot",
    "tweetmemebot",
    "twitterbot",
    "undrip bot",
    "void-bot",
    "voilabot",
    "vwbot_k",
    "wepbot",
    "who.is bot",
    "wikiobot",
    "woriobot",
    "yandexbot",
    "yesupbot",
    "yodaobot",
    "yolinkbot",
];

const CRAWLER_NAMES: [&str; 164] = [
    "80legs",
    "ahoy",
    "anthill",
    "appie",
    "arale",
    "araneo",
    "ariadne",
    "ask jeeves",
    "atn_worldwide",
    "atomz",
    "baidu",
    "baiduspider",
    "bjaaland",
    "bspider",
    "calif",
    "christcrawler",
    "cmc",
    "combine",
    "cosmos",
    "crawler",
    "crawlpaper",
    "curl",
    "curl_image_client",
    "cusco",
    "cyberspyder",
    "cydralspider",
    "desertrealm",
    "digger",
    "downloadexpress",
    "dwcp",
    "ebiness",
    "ecollector",
    "esculapio",
    "esther",
    "fastcrawler",
    "fdse",
    "felix ide",
    "fido",
    "fouineur",
    "freecrawl",
    "gammaspider",
    "gazz",
    "gcreep",
    "getterrobo-plus",
    "golem",
    "grabber",
    "griffon",
    "gromit",
    "gulliver",
    "gulper",
    "hamahakki",
    "havindex",
    "hotwired",
    "htdig",
    "ia_archiver",
    "image.kapsi.net",
    "informant",
    "infospiders",
    "ingrid",
    "inspectorwww",
    "iron33",
    "jcrawler",
    "jeeves",
    "jobo",
    "kdd-explorer",
    "kit-fireball",
    "label-grabber",
    "larbin",
    "legs",
    "linkidator",
    "linkwalker",
    "lockon",
    "logo_gif_crawler",
    "lwp-trivial",
    "marvin",
    "mattie",
    "mediafox",
    "mediapartners-google",
    "merzscope",
    "mindcrawler",
    "moget",
    "motor",
    "muncher",
    "muninn",
    "muscatferret",
    "mwdsearch",
    "nec-meshexplorer",
    "nederland.zoek",
    "netscoop",
    "newscan-online",
    "objectssearch",
    "occam",
    "orbsearch",
    "packrat",
    "pageboy",
    "pagesinventory",
    "parasite",
    "patric",
    "pegasus",
    "perlcrawler",
    "phpdig",
    "piltdownman",
    "pimptrain",
    "pjspider",
    "plumtreewebaccessor",
    "portalbspider",
    "raven",
    "rhcs",
    "roadrunner",
    "robbie",
    "robi",
    "robocrawl",
    "robofox",
    "scooter",
    "search-au",
    "searchprocess",
    "senrigan",
    "shagseeker",
    "sharp-info-agent",
    "sift",
    "site valet",
    "skymob",
    "slcrawler",
    "slurp",
    "snooper",
    "speedy",
    "spiderline",
    "spider_monkey",
    "suke",
    "tach_bw",
    "templeton",
    "teoma",
    "t-h-u-n-d-e-r-s-t-o-n-e",
    "titin",
    "topiclink",
    "udmsearch",
    "udmsearch",
    "ukonline",
    "urlck",
    "valkyrie libwww-perl",
    "verticrawl",
    "victoria",
    "voyager",
    "wapspider",
    "webbandit",
    "webcatcher",
    "webmechanic",
    "webmoose",
    "webquest",
    "webreaper",
    "webs",
    "webscout",
    "webspider",
    "webwalker",
    "wget",
    "whowhere",
    "winona",
    "wlm",
    "wolp",
    "wwwc",
    "www.sygol.com",
    "xget",
    "yahoo! slurp",
    "yeti",
];

/// Given a user agent `String` determine whether it is a web scaping bot.
pub fn user_agent_is_bot(user_agent: &String) -> bool {
    let lower_case: String = user_agent.to_lowercase();
    let bot = if !user_agent.contains("bot") {
        false
    } else {
        BOT_NAMES
            .iter()
            .find(|&name| lower_case.contains(name))
            .is_some()
    };

    if bot {
        true
    } else {
        CRAWLER_NAMES
            .iter()
            .find(|&name| lower_case.contains(name))
            .is_some()
    }
}
